name: 测试使用

on:
    schedule:
        - cron: "20 * * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                python-version: '3.10'
                  
            - name: "运行 什么值得买签到"
              run: python3 generate_build_script.py --os ubuntu  --os-version 22.04  --python 3.10.15  --pytorch 2.0.1 --cuda 11.7  --cuda-flavor   devel
